require("polyester.options")
require("polyester.keymaps")
require("polyester.flash")
require("polyester.colorscheme")
require("polyester.neorg")
require("polyester.cmp")
require("polyester.lsp")
require("polyester.telescope")
require("polyester.nvim-web-devicons")
require("polyester.treesitter")
require("polyester.autopairs")
-- require("polyester.hover")
require("polyester.comment")
require("polyester.gitsigns")
require("polyester.nvim-tree")
require("polyester.bufferline")
require("polyester.dashboard")
-- require("polyester.toggleterm")
-- require("polyester.trouble")
require("polyester.which-key")
-- require("polyester.nvim-ufo")
require("polyester.lualine")
-- require("polyester.fidget")

-- ALWAYS KEEP THIS AT THE BOTTOM
require("polyester.colorizer")
